### ISSUE TITLE
Code generator based on yaml

### ISSUE THREAD

**Issue by LucasDFranchi** [LucasDFranchi/Titaniumv2#5]
To assist users who may be unfamiliar with memory area creation, it's important to offer a more user-friendly interface. One viable option is to provide a YAML file that can be transformed into a C++ file using a Python script.

This approach allows users to define memory areas in a human-readable format, making it easier for them to specify their requirements. By leveraging a Python script to convert the YAML definitions into C++ code, the process becomes streamlined and less error-prone.

For instance, a YAML file could look like this:

```yaml
- name: MemoryArea1
  size: 1024
  attributes: ReadWrite

- name: MemoryArea2
  size: 2048
  attributes: Read
```

The accompanying Python script could parse this YAML file and generate the corresponding C++ code:

```cpp
MemoryArea MemoryArea1(1024, MemoryAttributes::ReadWrite);
MemoryArea MemoryArea2(2048, MemoryAttributes::Read);
```

This approach enhances accessibility and minimizes potential mistakes, while maintaining the shared core operations across classes.
